<?php

namespace Tests\Feature;

use App\Models\Shop\Category;
use App\Repository\Breadcrumbs\Shop\CategoryBreadcrumb;
use App\Repository\CategoryRepository as Repository;
use Database\Seeders\CategorySeeder;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class CategoryRepositoryTest extends TestCase
{

//    use RefreshDatabase, DatabaseMigrations;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->seed(CategorySeeder::class);
    }

    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function testgetFromUrl()
    {
        $category = Category::find(rand(2, 99));
        $repo = new Repository(new CategoryBreadcrumb());
        $model = $repo->getFromUrl($category->url);
        $this->assertInstanceOf(Category::class, $model);
    }
}
