<?php

namespace App\Repository\Breadcrumbs\Admin;

use App\Interfaces\RowGetteble;

class ProductBreadcrumb extends CategoryBreadcrumb
{
    public function getBreadcrumb(RowGetteble $model)
    {
        parent::getBreadcrumb($model); // TODO: Change the autogenerated stub
    }
}
