<?php

namespace Tests\Controllers\Feature;

use App\Models\Shop\Category;
use App\Models\Shop\Offer;
use App\Models\Shop\Product;
use Database\Seeders\CategorySeeder;
use Database\Seeders\PropertySeeder;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class CatalogControllerTest extends TestCase
{

//    use DatabaseMigrations;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->seed(CategorySeeder::class);
        Product::factory(500)->create();
        Offer::factory(2500)->create();
        $this->seed(PropertySeeder::class);

    }


    public function testindex()
    {
        $response = $this->get('/catalog');
        $response->assertStatus(200);
    }

    public function test404()
    {
        $response = $this->get('/catalog/frnef/rgerfewe/hgf/fgrfewf/grefwe');
        $response->assertStatus(404);
    }

    public function testlist()
    {
        $category = Category::find(rand(2, 99));
        $response = $this->get($category->url);
        $response->assertStatus(200);
    }

    public function testdetail()
    {
        $category = Category::find(rand(2, 99));
        $response = $this->get($category->url);
        $response->assertStatus(200);
    }

}
